version: '3.8'

services:
  examservice.api:
    container_name: examservice.api
    build:
      context: .
      dockerfile: ExamService/ExamService.API/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__ExamServiceDbConnection=Server=examdb,1433;Database=ExamServiceDb;User=sa;Password=Admin@1234;TrustServerCertificate=True;
    restart: on-failure

  examdb:
    container_name: examservice.mssql
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "Admin@1234"
      MSQLL_PID: "Express"
      ACCEPT_EULA: "Y"
    ports:
      - "11433:1433"
    healthcheck:
      test: ["CMD-SHELL", "sqlcmd -S localhost -U sa -P Admin@1234 -Q 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - examdata:/var/opt/mssql

volumes:
  examdata:
