@ExamService.API_HostAddress = https://localhost:7006

GET {{ExamService.API_HostAddress}}/
Accept: application/json

###

### 1. Generate a dev token
POST {{ExamService.API_HostAddress}}/dev-token
Accept: application/json

### 2. Use the token below (after pasting into Bearer) to call a secured endpoint
GET {{ExamService.API_HostAddress}}/api/v1/subjects
Authorization: Bearer goes here . . . . 
Accept: application/json
